spring:
  application:
    name: BookStoreBackend
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore_db?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  validation:
    minimum-price: 0.0
